package com.example.dell.chat.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.chat.bean.PersonalState;
import com.example.dell.chat.bean.User;

import com.example.dell.chat.db.PersonalStateDao;
import com.example.dell.chat.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalStateDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PersonalStateDao personalStateDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalStateDaoConfig = daoConfigMap.get(PersonalStateDao.class).clone();
        personalStateDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personalStateDao = new PersonalStateDao(personalStateDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PersonalState.class, personalStateDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        personalStateDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public PersonalStateDao getPersonalStateDao() {
        return personalStateDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
