package com.example.dell.chat.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.chat.bean.PersonalState;
import com.example.dell.chat.bean.User;
import com.example.dell.chat.bean.Chat;
import com.example.dell.chat.bean.Message;

import com.example.dell.chat.db.PersonalStateDao;
import com.example.dell.chat.db.UserDao;
import com.example.dell.chat.db.ChatDao;
import com.example.dell.chat.db.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalStateDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig chatDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final PersonalStateDao personalStateDao;
    private final UserDao userDao;
    private final ChatDao chatDao;
    private final MessageDao messageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalStateDaoConfig = daoConfigMap.get(PersonalStateDao.class).clone();
        personalStateDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        personalStateDao = new PersonalStateDao(personalStateDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(PersonalState.class, personalStateDao);
        registerDao(User.class, userDao);
        registerDao(Chat.class, chatDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        personalStateDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        chatDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public PersonalStateDao getPersonalStateDao() {
        return personalStateDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
