package com.example.dell.chat.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.dell.chat.bean.Message;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE".
*/
public class MessageDao extends AbstractDao<Message, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity Message.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, int.class, "user_id", false, "USER_ID");
        public final static Property Contact_id = new Property(2, int.class, "contact_id", false, "CONTACT_ID");
        public final static Property Image_path = new Property(3, String.class, "image_path", false, "IMAGE_PATH");
        public final static Property Contact_name = new Property(4, String.class, "contact_name", false, "CONTACT_NAME");
        public final static Property Latest_content = new Property(5, String.class, "latest_content", false, "LATEST_CONTENT");
        public final static Property Latest_time = new Property(6, long.class, "latest_time", false, "LATEST_TIME");
        public final static Property Unread = new Property(7, int.class, "unread", false, "UNREAD");
    };


    public MessageDao(DaoConfig config) {
        super(config);
    }
    
    public MessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: user_id
                "\"CONTACT_ID\" INTEGER NOT NULL ," + // 2: contact_id
                "\"IMAGE_PATH\" TEXT," + // 3: image_path
                "\"CONTACT_NAME\" TEXT," + // 4: contact_name
                "\"LATEST_CONTENT\" TEXT," + // 5: latest_content
                "\"LATEST_TIME\" INTEGER NOT NULL ," + // 6: latest_time
                "\"UNREAD\" INTEGER NOT NULL );"); // 7: unread
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindLong(3, entity.getContact_id());
 
        String image_path = entity.getImage_path();
        if (image_path != null) {
            stmt.bindString(4, image_path);
        }
 
        String contact_name = entity.getContact_name();
        if (contact_name != null) {
            stmt.bindString(5, contact_name);
        }
 
        String latest_content = entity.getLatest_content();
        if (latest_content != null) {
            stmt.bindString(6, latest_content);
        }
        stmt.bindLong(7, entity.getLatest_time());
        stmt.bindLong(8, entity.getUnread());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindLong(3, entity.getContact_id());
 
        String image_path = entity.getImage_path();
        if (image_path != null) {
            stmt.bindString(4, image_path);
        }
 
        String contact_name = entity.getContact_name();
        if (contact_name != null) {
            stmt.bindString(5, contact_name);
        }
 
        String latest_content = entity.getLatest_content();
        if (latest_content != null) {
            stmt.bindString(6, latest_content);
        }
        stmt.bindLong(7, entity.getLatest_time());
        stmt.bindLong(8, entity.getUnread());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Message readEntity(Cursor cursor, int offset) {
        Message entity = new Message( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // user_id
            cursor.getInt(offset + 2), // contact_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // image_path
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // contact_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // latest_content
            cursor.getLong(offset + 6), // latest_time
            cursor.getInt(offset + 7) // unread
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Message entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getInt(offset + 1));
        entity.setContact_id(cursor.getInt(offset + 2));
        entity.setImage_path(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContact_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLatest_content(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLatest_time(cursor.getLong(offset + 6));
        entity.setUnread(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Message entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Message entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
